In [2]:
import numpy as np

In [3]:
my_list=[1,2,3,4,5]
my_first_array = np.array(my_list)
print(my_first_array *2)
print(type(my_first_array))

[ 2  4  6  8 10]
<class 'numpy.ndarray'>


In [4]:
distance_in_kms = [2.1, 4.9, 5.6, 7.8] 

In [5]:
distance_in_ms = [item*1000 for item in distance_in_kms]
print(distance_in_ms)

[2100.0, 4900.0, 5600.0, 7800.0]


In [6]:
print(np.array(distance_in_kms)*1000)

[2100. 4900. 5600. 7800.]


In [7]:
print(len(np.array(distance_in_kms)))

4


In [8]:
type(range(1,10,2))

range

In [9]:
a = np.arange(1, 10, 4)
b=range(1,10,4)
print(a)
print(type(a))
print(b)
print(type(b))

[1 5 9]
<class 'numpy.ndarray'>
range(1, 10, 4)
<class 'range'>


In [10]:
a_2 = range(1,10)
print(a_2)

range(1, 10)


In [11]:
#default step of 1 and start from 0
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [12]:
x = np.arange(0.5, 13.2, 0.7)
print(x)

[ 0.5  1.2  1.9  2.6  3.3  4.   4.7  5.4  6.1  6.8  7.5  8.2  8.9  9.6
 10.3 11.  11.7 12.4 13.1]


In [13]:
int_array = np.array([1.,2,3,4,5])
print(int_array.dtype)
print(int_array.ndim)


float64
1


In [15]:
print(int_array[:-1])

[ 1.  2.  3.  4.]


In [16]:
print(int_array[::-1])

[ 5.  4.  3.  2.  1.]


In [17]:
array_of_floats = np.array([5.5, 5.4, 4.11, 6.0, 6.2, 5.8, 7.1], float)

In [18]:
print(array_of_floats.mean())

5.73


In [19]:
print(np.median(array_of_floats))

5.8


In [20]:
print(array_of_floats.max())

7.1


In [21]:
print(array_of_floats.argmax())

6


In [22]:
print(array_of_floats>5.5) 

[False False False  True  True  True  True]


In [23]:
greater_than = a>5.5
print(any(greater_than))
print(all(greater_than))

True
False


In [ ]:
a

In [24]:
first_array = np.array([1,2,3])
second_array = np.array([4,5,6])
print(np.concatenate((first_array,second_array)))

[1 2 3 4 5 6]


In [25]:
first_matrix = np.arange(30).reshape(5,6)

In [26]:
print(first_matrix)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [27]:
print(np.identity(3))

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [29]:
#initiate array of ones and zeros
a = np.ones((4,4),dtype=int)
print(a)


[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [30]:
#max of each row
print("The max is : {0} {1}".format(first_matrix.max(axis=0),first_matrix.max(axis=1)))

The max is : [24 25 26 27 28 29] [ 5 11 17 23 29]


In [31]:
#sum of each row
print("The sum is : {0}".format(first_matrix.sum(axis=1)))


The sum is : [ 15  51  87 123 159]


In [32]:
#np arrays vs lists

#adding lists
first_list = [1,2,3]
second_list = [4,5,6]

print(first_list+second_list) #concatenates
print(np.array(first_list) + np.array(second_list)) #element-wise adddition

[1, 2, 3, 4, 5, 6]
[5 7 9]


In [ ]:
print(np.array(first_list)/np.array(second_list)) 


In [ ]:
help(np.arange)